package helloworld;
import helloworld.Accounts;
import helloworld.model.Transaction;
import helloworld.model.Account;
import helloworld.service.BankingService;
import helloworld.model.TransactionType;

import javax.swing.*;
import java.awt.*;
import java.util.List;
import java.util.Map;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class BankingGUI extends javax.swing.JFrame {
    
    private final BankingService bankService = new BankingService();
    private final Transaction transaction = new Transaction(TransactionType.DEPOSIT,20000,2000);


    /**
     * Creates new form BankingGUI
     */
    public BankingGUI() {
        initComponents();
       
        
    }
     
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSelectAccount = new javax.swing.JButton();
        btnCreateAccount = new javax.swing.JButton();
        btnListAllHistory = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setFocusableWindowState(false);
        setPreferredSize(new java.awt.Dimension(400, 300));
        setSize(new java.awt.Dimension(400, 300));

        mainPanel.setBackground(new java.awt.Color(0, 51, 51));
        mainPanel.setDoubleBuffered(false);
        mainPanel.setFocusCycleRoot(true);
        mainPanel.setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setEnabled(false);
        jPanel2.setFocusCycleRoot(true);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to iBANKING App👍!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        btnSelectAccount.setBackground(new java.awt.Color(0, 0, 204));
        btnSelectAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnSelectAccount.setText("1. Select Account");
        btnSelectAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAccountActionPerformed(evt);
            }
        });

        btnCreateAccount.setBackground(new java.awt.Color(0, 0, 204));
        btnCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateAccount.setText("2. Create Account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });

        btnListAllHistory.setBackground(new java.awt.Color(0, 0, 204));
        btnListAllHistory.setForeground(new java.awt.Color(255, 255, 255));
        btnListAllHistory.setText("3. List Account");
        btnListAllHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListAllHistoryActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(0, 0, 204));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("0. Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateAccount)
                    .addComponent(btnSelectAccount)
                    .addComponent(btnExit)
                    .addComponent(btnListAllHistory))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSelectAccount)
                .addGap(18, 18, 18)
                .addComponent(btnCreateAccount)
                .addGap(18, 18, 18)
                .addComponent(btnListAllHistory)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 349, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAccountActionPerformed
        // TODO add your handling code here:
       
    SelectAccount selectAccountFrame = new SelectAccount(bankService,transaction);
    selectAccountFrame.setVisible(true);
      // Optional: close the main banking GUI if you want

    }//GEN-LAST:event_btnSelectAccountActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
 Accounts accountsGui = new Accounts(bankService);
        accountsGui.setVisible(true);
        this.dispose();         // TODO add your handling code here:
 
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void btnListAllHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListAllHistoryActionPerformed

Map<String, Account> accounts = bankService.getAllAccounts();

    if (accounts.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No accounts found.", "Accounts", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    StringBuilder sb = new StringBuilder();
    for (Account acc : accounts.values()) {
        sb.append(acc).append("\n");
    }

    JOptionPane.showMessageDialog(this, sb.toString(), "All Accounts", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnListAllHistoryActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      SwingUtilities.invokeLater(() -> new BankingGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnListAllHistory;
    private javax.swing.JButton btnSelectAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

/*void setLocationRelativeTo(){
   throw new UnsupportedOperationException("Operation not yet supported!");
 }*/
}
